version: '3.8'
services:
  go-viki:
    image: alpine:3.20
    container_name: go-viki
    working_dir: /app
    restart: ${RESTART_POLICY}
    env_file:
      - .env.prod
    environment:
      - TZ
      - SERVER_PORT
      - MONGODB_URL
      - MONGODB_DATABASE
      - MONGODB_USER
      - MONGODB_PASS
      - JWT_SECRET
      - JWT_EXPIRATION_MS
    ports:
      - ${BROXY_SERVER_PORT}:${BROXY_SERVER_PORT}
    volumes:
      - ../build/broxy:/app/server
      - ../templates:/app/templates
      - ../.env.prod:/app/.env
      - ../go.mod:/app/go.mod
    command: ./server
    networks:
      - ukkera
networks:
  ukkera:
    external: true